"""Init db from empty

Revision ID: 440575a4808c
Revises: None
Create Date: 2016-04-18 20:11:39.246857
"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '440575a4808c'
down_revision = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id_', sa.Integer(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('avatar', sa.String(length=100), nullable=True),
    sa.Column('github_id', sa.String(length=20), nullable=True),
    sa.Column('github_username', sa.String(length=50), nullable=True),
    sa.Column('role', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id_'),
    sa.UniqueConstraint('github_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('sighs',
    sa.Column('id_', sa.Integer(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('type_', sa.Enum('sigh', 'wtf', 'fml', name='content_types'), nullable=False),
    sa.Column('is_anonymous', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id_'], ),
    sa.PrimaryKeyConstraint('id_')
    )
    op.create_table('tags',
    sa.Column('id_', sa.Integer(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('display_name', sa.String(length=50), nullable=False),
    sa.Column('searchable_name', sa.String(length=500), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id_'], ),
    sa.PrimaryKeyConstraint('id_'),
    sa.UniqueConstraint('display_name'),
    sa.UniqueConstraint('searchable_name')
    )
    op.create_table('comments',
    sa.Column('id_', sa.Integer(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sigh_id', sa.Integer(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id_'], ),
    sa.ForeignKeyConstraint(['sigh_id'], ['sighs.id_'], ),
    sa.PrimaryKeyConstraint('id_')
    )
    op.create_table('tag_identifier',
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.Column('sigh_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sigh_id'], ['sighs.id_'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id_'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tag_identifier')
    op.drop_table('comments')
    op.drop_table('tags')
    op.drop_table('sighs')
    op.drop_table('users')
    ### end Alembic commands ###

